#!/usr/bin/env python

import os
import sys

import newrelic.agent
newrelic.agent.initialize('./app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/newrelic-2.30.0.27/newrelic/newrelic.ini')

os.environ['DJANGO_SETTINGS_MODULE'] = 'openshift.settings'
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'openshift'))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "openshift/")))
virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except:
    pass

# import django.core.handlers.wsgi
# application = django.core.handlers.wsgi.WSGIHandler()
from django.core.wsgi import get_wsgi_application
from raven.contrib.django.raven_compat.middleware.wsgi import Sentry
application = Sentry(get_wsgi_application())
